todolist/tarefas/urls.py
from django.urls import path
from todolist.tarefas import views

app_name = 'tarefas'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:tarefa_id>', views.detalhe, name='detalhe'),
    path('apagar/<int:tarefa_id>', views.apagar, name='apagar'),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

from todolist.tarefas.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('tarefas/', include('todolist.tarefas.urls')),
]

todolist/tarefas/models.py
from django.db import models


class Tarefa(models.Model):
    nome = models.CharField(max_length=128)
    feita = models.BooleanField(default=False)

todolist/tarefas/forms.py
from django.forms.models import ModelForm

from todolist.tarefas.models import Tarefa


class TarefaNovaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome']


class TarefaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome', 'feita']

todolist/tarefas/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from todolist.tarefas.forms import TarefaNovaForm, TarefaForm
from django.urls import reverse

from todolist.tarefas.models import Tarefa


def home(request):
    tarefas_pendentes = Tarefa.objects.filter(feita=False).all()
    tarefas_feitas = Tarefa.objects.filter(feita=True).all()
    if request.method == 'POST':
        form = TarefaNovaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tarefas:home'))
        else:
            return render(
                request, 'tarefas/home.html',
                {
                    'form': form,
                    'tarefas_pendentes': tarefas_pendentes,
                    'tarefas_feitas': tarefas_feitas
                },
                status=400)
    return render(
        request, 'tarefas/home.html',
        {
          'tarefas_pendentes': tarefas_pendentes,
          'tarefas_feitas': tarefas_feitas,
        }
        )


def detalhe(request, tarefa_id):
    if request.method == 'POST':
        tarefa = Tarefa.objects.get(id=tarefa_id)
        form = TarefaForm(request.POST, instance=tarefa)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('tarefas:home'))


def apagar(request, tarefa_id):
    if request.method == 'POST':
        Tarefa.objects.filter(id=tarefa_id).delete()
    return HttpResponseRedirect(reverse('tarefas:home'))

todolist/tarefas/templates/tarefas/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>TodoList</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
<!--            Rotina para incluir tarefa-->
                <h1 class="mt-5">Incluir Tarefa</h1>
                <form action="{% url 'tarefas:home' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input name="nome" type="text" class="form-control" placeholder="Descreva sua tarefa"
                               aria-label="Descreva sua tarefa" aria-describedby="button-addon2">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                    <small class="text-danger">{{ form.nome.errors }}</small>
                </form>

<!--            Rotina para listar tarefas pendentes-->
                <h3 class="mt-5">Tarefas Pendentes</h3>
                {% for tarefa in tarefas_pendentes %}
                <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input name="nome" type="text" class="form-control" placeholder="{{ tarefa.nome }}"
                               required="required" aria-label="Descreva sua tarefa" value="{{ tarefa.nome }}">
                        <input type="hidden" value="checked" name="feita">
                        <button type="submit" class="btn btn-success">Marcar como Feita</button>
                    </div>
                </form>
                {% empty %}
                <p>Não há tarefas pendentes</p>
                {% endfor %}

<!--            Rotina para apagar e listar tarefas concluídas-->
                <h3 class="mt-5">Tarefas Concluídas</h3>
                {% for tarefa in tarefas_feitas %}
                <div class="row">
                    <div class="col-1">
<!--            Apagar tarefas concluídas-->
                        <form action="{% url 'tarefas:apagar' tarefa_id=tarefa.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <button type="submit" class="btn btn-danger">Apagar</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-11">
<!--            Listar tarefas concluídas-->
                        <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <input name="nome" type="text" class="form-control" placeholder="{{ tarefa.nome }}"
                                       required="required" aria-label="Descreva sua tarefa" value="{{ tarefa.nome }}">
                                <button type="submit" class="btn btn-warning">Marcar como Pendente</button>
                            </div>
                        </form>
                    </div>
                </div>
                {% empty %}
                <p>Não há tarefas concluídas</p>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>